baseURL = "https://vinayreddybv.github.io/"
languageCode = "en"
title = "B. Vinay Reddy"
theme = "PaperMod"

# ✅ Include custom CSS file
customCSS = ["css/custom.css"]

[params]
  # ------------------------------
  # PROFILE MODE CONFIGURATION
  # ------------------------------
  [params.profileMode]
    enabled = true
    title = "B. Vinay Reddy"
    subtitle = "Independent Tax Consultant, Blogger & Research Enthusiast"
    imageUrl = "images/profile.jpg"
    imageTitle = "B. Vinay Reddy Profile Photo"
    imageWidth = 200
    imageHeight = 200
    buttons = [] # Keep empty for no buttons

  # ------------------------------
  # THEME ACCENT COLOR (Brand Blue)
  # ------------------------------
  [params.assets]
    primaryColor = "#0078ff"

  # ------------------------------
  # SOCIAL ICONS (correct key)
  # ------------------------------
  [[params.socialIcons]]
    name = "email"
    url = "mailto:help@bvinayreddy.com"

  [[params.socialIcons]]
    name = "facebook"
    url = "https://www.facebook.com/BanappagariVinayReddy"

  [[params.socialIcons]]
    name = "x"
    url = "https://x.com/VinayReddyBV"

  [[params.socialIcons]]
    name = "instagram"
    url = "https://www.instagram.com/vinayreddybv/"

  [[params.socialIcons]]
    name = "link"
    url = "https://taxguru.in/author/bvreddy/"

# ------------------------------
# MAIN MENU CONFIGURATION
# ------------------------------
[[menu.main]]
  identifier = "blog"
  name = "Blog"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 2

[[menu.main]]
  identifier = "resume"
  name = "Resume"
  url = "/resume/"
  weight = 3
