baseURL = "https://vinayreddybv.github.io/"
languageCode = "en"
title = "B. Vinay Reddy"
theme = "PaperMod"

# Custom CSS
customCSS = ["css/custom.css"]

[params]
  env = "production"
  defaultTheme = "light"     # no dark mode toggle
  disableThemeToggle = true
  showReadingTime = true
  showPostNavLinks = true
  showBreadCrumbs = true
  showCodeCopyButtons = true
  showToc = false
  comments = false
  showMenu = true
  collapseMenu = true

  # --- SEO / Author Info ---
  author = "B. Vinay Reddy"
  description = "Writer & Advocate sharing insights on RTI, Legal Awareness, and People’s Rights."
  keywords = ["RTI", "Consumer Rights", "Legal Awareness", "Transparency"]

  # --- Favicon & Logo ---
  assets = { favicon = "/images/profile.jpg", favicon16x16 = "/images/profile.jpg", favicon32x32 = "/images/profile.jpg" }

  # --- Profile Mode (Homepage) ---
  [params.profileMode]
    enabled = true
    title = "B. Vinay Reddy"
    subtitle = "Writer | Law Student | RTI for Change | Voice for Accountability"
    imageUrl = "/images/profile.jpg"
    imageTitle = "Profile Picture"
    imageWidth = 150
    imageHeight = 150
    buttons = []

  # --- Social Links (for homepage icons) ---
  [[params.socialIcons]]
    name = "email"
    url = "mailto:help@bvinayreddy.com"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/bvinayreddy/"

  [[params.socialIcons]]
    name = "x-twitter"
    url = "https://x.com/VinayReddyBV"

  [[params.socialIcons]]
    name = "facebook"
    url = "https://www.facebook.com/BanappagariVinayReddy"

  [[params.socialIcons]]
    name = "instagram"
    url = "https://www.instagram.com/vinayreddybv/"

  [[params.socialIcons]]
    name = "link"
    url = "https://www.bvinayreddy.com/"

# --- Menu ---
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "rti"
    name = "RTI"
    url = "/rti/"
    weight = 2

  [[menu.main]]
    identifier = "legal-awareness"
    name = "Legal Awareness"
    url = "/legal-awareness/"
    weight = 3

  [[menu.main]]
    identifier = "blogs"
    name = "Blogs"
    url = "/blogs/"
    weight = 4

  [[menu.main]]
    identifier = "contact"
    name = "Contact Me"
    url = "/contact/"
    weight = 5

[markup.goldmark.renderer]
  unsafe = true
