baseURL = "https://vinayreddybv.github.io/"
languageCode = "en"
title = "B. Vinay Reddy"
theme = "PaperMod"

# Custom CSS
customCSS = ["css/custom.css"]

[params]
  env = "production"
  defaultTheme = "light"
  showReadingTime = true
  showPostNavLinks = true
  showBreadCrumbs = true
  showCodeCopyButtons = true
  showToc = false
  comments = false

  [params.profileMode]
    enabled = false

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "rti"
    name = "RTI"
    url = "/rti/"
    weight = 2

  [[menu.main]]
    identifier = "consumer"
    name = "Consumer Court"
    url = "/consumer-court/"
    weight = 3

  [[menu.main]]
    identifier = "others"
    name = "Others"
    url = "/others/"
    weight = 4

  [[menu.main]]
    identifier = "contact"
    name = "Contact Me"
    url = "/contact/"
    weight = 5

[markup.goldmark.renderer]
  unsafe = true

