backend:
  name: github
  repo: vinayreddybv/vinayreddybv.github.io
  branch: main
  base_url: https://auth.netlify.com
  auth_endpoint: /auth
  client_id: Ov23libKjIYPXOOOEmAM


media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }

  - name: "pages"
    label: "Pages"
    folder: "content"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
